/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * FinTech Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * UsageLimitRestController as REST API
 *
 * <p>Exposes REST endpoints for the UsageLimit entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>FinTech Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core digital banking, payments, wallets, lending, investments, FX, compliance, and risk management capabilities.</td></tr>
 *          <tr><td>industry</td><td>FinTech</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	UsageLimitBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateUsageLimitCommand</li>
 *      <li></li>UpdateUsageLimitCommand</li>
 *      <liDeleteUsageLimitCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/UsageLimit")
public class UsageLimitRestController extends BaseSpringRestController {

    /**
     * Handles create a UsageLimit.  if not key provided, calls create, otherwise calls save
     * @param		UsageLimit	usageLimit
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateUsageLimitCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = UsageLimitService.getUsageLimitInstance().createUsageLimit( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a UsageLimit.  if no key provided, calls create, otherwise calls save
     * @param		UsageLimit usageLimit
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateUsageLimitCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateUsageLimitCommand
			// -----------------------------------------------
			completableFuture = UsageLimitService.getUsageLimitInstance().updateUsageLimit(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "UsageLimitController:update() - successfully update UsageLimit - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a UsageLimit entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteUsageLimitCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	UsageLimitService delegate = UsageLimitService.getUsageLimitInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted UsageLimit with key " + command.getUsageLimitId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a UsageLimit using a UUID
     * @param		UUID uuid 
     * @return		UsageLimit
     */    
    @GetMapping("/load")
    public UsageLimit load( @RequestParam(required=true) UUID uuid ) {    	
    	UsageLimit entity = null;

    	try {  
    		entity = UsageLimitService.getUsageLimitInstance().getUsageLimit( new UsageLimitFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load UsageLimit using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all UsageLimit business objects
     * @return		Set<UsageLimit>
     */
    @GetMapping("/")
    public List<UsageLimit> loadAll() {                
    	List<UsageLimit> usageLimitList = null;
        
    	try {
            // load the UsageLimit
            usageLimitList = UsageLimitService.getUsageLimitInstance().getAllUsageLimit();
            
            if ( usageLimitList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all UsageLimits" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all UsageLimits ", exc );
        	return null;
        }

        return usageLimitList;
                            
    }

    /**
     * save PricingPlan on UsageLimit
     * @param		command AssignPricingPlanToUsageLimitCommand
     */     
	@PutMapping("/assignPricingPlan")
	public void assignPricingPlan( @RequestBody AssignPricingPlanToUsageLimitCommand command ) {
		try {
			UsageLimitService.getUsageLimitInstance().assignPricingPlan( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign PricingPlan", exc );
        }
	}

    /**
     * unassign PricingPlan on UsageLimit
     * @param		 command UnAssignPricingPlanFromUsageLimitCommand
     */     
	@PutMapping("/unAssignPricingPlan")
	public void unAssignPricingPlan( @RequestBody(required=true)  UnAssignPricingPlanFromUsageLimitCommand command ) {
		try {
			UsageLimitService.getUsageLimitInstance().unAssignPricingPlan( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign PricingPlan", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected UsageLimit usageLimit = null;
    private static final Logger LOGGER = Logger.getLogger(UsageLimitRestController.class.getName());
    
}
